service: ${env:APP_NAME}
variablesResolutionMode: 20210326

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-sam
  - serverless-plugin-canary-deployments
  - serverless-plugin-resource-tagging

provider:
  name: aws
  region: ${env:AWS_REGION}
  lambdaHashingVersion: 20201221
  environment: ${ssm:/aws/reference/secretsmanager/${env:SECRET_NAME}}
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket: ${env:LAMBDA_DEPLOYMENT_BUCKET}
  deploymentPrefix: ${self:service}
  stackTags:
    App: ${env:APP_NAME}
    Env: ${env:ENVIRONMENT_NAME}
  layers:
    - arn:aws:lambda:${env:AWS_REGION}:${env:ACCOUNT_ID}:layer:chalice-python:1
    - arn:aws:lambda:${env:AWS_REGION}:${env:ACCOUNT_ID}:layer:boto3-python:1

functions:
  app:
    handler: ${env:LAMBDA_HANDLER}
    name: ${self:service}
    runtime: ${env:LAMBDA_RUNTIME}
    memorySize: ${env:LAMBDA_MEMORY_SIZE}
    timeout: ${env:LAMBDA_TIMEOUT}
    provisionedConcurrency: ${env:LAMBDA_PROVISIONED_CONCURRENCY}
    reservedConcurrency: ${env:LAMBDA_RESERVED_CONCURRENCY}
    role: arn:aws:iam::${env:ACCOUNT_ID}:role/LambdaExecutionRole-${self:service}-${env:ENVIRONMENT_NAME}
    events:
      - sqs: ${env:SQS_QUEUE_ARN_0}
    deploymentSettings:
      type: ${env:LAMBDA_DEPLOYMENT_PREFERENCE_TYPE}
      alias: Live
    vpc:
      securityGroupIds:
        - ${env:LAMBDA_SECURITY_GROUP_ID}
      subnetIds:
        - ${env:SUBNET_ID_0}
        - ${env:SUBNET_ID_1}
    environment:
      APP_ENV: ${env:ENVIRONMENT_NAME}
      DEBUG: true
      LOG_LEVEL: info
      REGION_NAME: ${env:AWS_REGION}